technoadvance3/technoadvance3/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('techx.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

technoadvance3/techx/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'techno'
urlpatterns = [
    url(r'workshops/BridgeDesign/$',views.BridgeDesign,name='BridgeDesign'),
	url(r'workshops/EthicalHacking/$',views.EthicalHacking,name='EthicalHacking'),
	url(r'workshops/Android/$',views.android,name='Android App Development'),
	url(r'workshops/IoT/$',views.IoT,name='IoT'),
	url(r'workshops/Digital/$',views.digital,name='Digital Marketing'),
	url(r'workshops/ML/$',views.ml,name='Machine Learning'),
	url(r'workshops/CloudComputing/$',views.cloudComputing,name='CloudComputing'),
	url(r'workshops/(?P<id>[0-9]+)/$',views.workshops,name='workshops'),
	url(r'upcoming_events/(?P<id>[0-9]+)/$',views.upcoming_events,name='upcoming'),
	url(r'^request_a_workshop/$',views.request_a_workshop_view,name='request_a_workshop_view'),
	url(r'^upcoming_events_temporary/$',views.upcoming_events_temporary,name='upcoming_events_temporary'),	
	url(r'^become_a_campus_ambassador/$',views.become_a_campus_ambassador,name='become_a_campus_ambassador'),
	url(r'^about/$',views.about,name='about'),
	url(r'^workshop/$',views.workshop,name='workshop'),
	url(r'^contact_us/$',views.contact_us,name='contact_us'),
    url(r'^$',views.index,name='index'),

]
#become_a_campus_ambassador

technoadvance3/templates/become_a_campus_ambassador.html
{% extends "header3.html"%} 
{% load tags %}
{% load staticfiles %}
{% block content %}

   <style>
      body{
        font-family: 'Cardo', serif!important;
      }
      .content1 {
        background: linear-gradient(130deg, #07d9a3, #048fee);
        background-size: 400% 400%;
        -webkit-animation: gradient 16s ease infinite;
        animation: gradient 16s ease infinite;
        margin: auto;
        padding: 50px;
        width: 100%;
        max-width: 100%;
        min-width: 300px;
        margin-bottom: 10px;
        border-radius: 5px;
        box-shadow:0px 11px 18.33px 3.67px rgba(0, 0, 0, 0.10);
        color:#fff;
}
.content1 p, h3, h5, ul{
  color:#fff;
}

    </style>

<section class="banner full" style="padding: 0;min-height: 0vh;height: 60vh !important;">
        <article>
          <img src=" {% static 'img/be_a_campus_ambassador.jpg' %}" alt="" style="height:50%!important" />
          <div class="inner">
            <header class = "wow fadeInUp">
              <h3 style="font-size:61px !important;font-family: 'Josefin Sans', sans-serif;" > <strong>Campus Ambassador</strong> </h3>
              <p>Be a leader and represent us in your campus events.</p>
              <a href="{% url 'techno:about'  %}">
              </a>
            </header>
          </div>
        </article> 
      </section>

  
<div  id="">
 <div class="container"  id="about" style = "">
    <div class = "row">
      <div class = "col-lg-6 content1">
        <div class= "container">
        <div class="col-lg-12 content wow fadeInRight text-justify text-dark">
            <h3 style="color:#fff !important; font-weight: 400;">Diginique provides you the best opportunity to showcase your talent and polish your interpersonal as well as soft skills. </h3>
            <h3> </h3>
            <p>
              Having the motive to bring student leaders out of the box, making face and voice of an organization, providing learning opportunities, we help you develop various skills such as social media marketing, content marketing, organizing seminars, conducting workshops, vocational training etc.
            </p>
            <h5><strong>Oppurtunities</strong></h5>
            <ul>
              <li><i class="ion-android-checkmark-circle"></i>Enhance your skill</li>
              <li><i class="ion-android-checkmark-circle"></i>Represent your college </li>
              <li><i class="ion-android-checkmark-circle"></i>Improve your communication and managerial skills</li>
            </ul>
            <h5><strong>Responsibility</strong></h5>
            <ul>
              <li><i class="ion-android-checkmark-circle"></i>Organize Workshop </li>
              <li><i class="ion-android-checkmark-circle"></i>Publicity</li>
              <li><i class="ion-android-checkmark-circle"></i>Promotions</li>
            </ul>
            <h5><strong>Benefits</strong></h5>
            <ul>
              <li><i class="ion-android-checkmark-circle"></i>Internship Opportunities</li>
              <li><i class="ion-android-checkmark-circle"></i>Certificate of Appreciation </li>
              <li><i class="ion-android-checkmark-circle"></i>Goodie</li>
              <li><i class="ion-android-checkmark-circle"></i>Monetary Benefits  </li>

            </ul>
            
            <br>

          </div>
        </div>
      </div>

      <div class="col-lg-6" id="contact" style="">
       <div class= "container">
        <div class="col-lg-12 content wow fadeInRight">
            <div class="contact-about">
             <h5><strong>Fill out the form</strong></h5>
            <div class="form">
              <div id="sendmessage">Your message has been sent. Thank you!</div>
              <div id="errormessage"></div>
              <form action="" method="post" role="form" class="contactForm ">
                {% csrf_token %}
                <div class="form-row">
                  <div class="form-group col-lg-6">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:1" data-msg="Please enter your name." />
                    <div class="validation"></div>
                  </div>
                  <div class="form-group col-lg-6">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  
                  <div class="validation"></div>
                </div>
                </div>
                <div class="form-group">
                  <input type="Number" class="form-control" name="contact_number" id="contact_number" placeholder="Contact Number" data-rule="minlen:4" data-msg="Please enter a correct phone number." />
                  <div class="validation"></div>
                </div>
                
                
                <div class="form-group">
                  <input type="text" class="form-control" name="college" id="college" placeholder="College" data-rule="required" data-msg="Please enter your college." />
                  <div class="validation"></div>
                </div>
                <div class="form-group ">
                    <input type="text" class="form-control" name="department" id="department" placeholder="Department" data-rule="required" data-msg="Please enter your department." />
                    <div class="validation"></div>
                  </div>
                <div class="form-group">
                  <input type="text" class="form-control" name="city" id="city" placeholder="City" data-rule="required" data-msg="Please enter your location." />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <input type="Number" class="form-control" name="graduating_year" id="graduating_year" placeholder="Graduating Year" data-rule="minlen:4" data-msg="Please enter a correct Graduating Year." />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <textarea  class="form-control" name="permanent_address" rows="5"  data-rule="required" data-msg="Please enter your Permanent Address." placeholder="Permanent Address"></textarea>
                  <div class="validation"></div>
                </div>
                
                <div class="form-group">
                  <textarea class="form-control" name="past_experience" rows="5" data-rule="minlen:0" data-msg="" placeholder="Past Experience"></textarea>
                  <div class="validation"></div>
                </div>
                
                <input class="btn btn-outline-dark btn-block btn-block" type="submit" value="Submit" />
              </form>
            </div>
          </div>
        </div>
        <div class ="col-md-2"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

technoadvance3/templates/header3.html
{% load staticfiles %}
{% load tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Diginique</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700|Open+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Alegreya|Bitter|Cardo|Chivo|Cormorant+Garamond|Josefin+Sans|Nunito|Overpass|Proza+Libre|Raleway" rel="stylesheet">
  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style3.css' %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style1.css' %}" rel="stylesheet">
  
  <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">
  <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
    
</head>
<body class = "main">

  <!--==========================
    Header
  ============================-->

    <header id="header" class = "header-fixed-dobara">
    <div class="container-fluid">
      
      <div id="logo" class="pull-left" style="">
        <!--<h1><a href="{%url 'techno:index' %}" class="scrollto">Diginque</a></h1> -->
        <!-- Uncomment below if you prefer to use an image logo -->
        <a href="{%url 'techno:index' %}"><img src=" {% static 'img/Logos/diginique.jpg' %} " alt="" title="" style = "width:auto;height:55px;position: absolute;left:100px"></a>
      </div>
      <div class = "container">
      <nav id="nav-menu-container">
        <ul class="nav-menu float-right">
             <li class="menu-active"><a href="{%url 'techno:index' %}">Home</a></li>
             <li><a href=" {% url 'techno:about'  %}">About Us</a></li>
             <li><a href=" {% url 'techno:workshop'  %}">Workshops</a></li>
             <li><a href=" {% url 'techno:upcoming_events_temporary' %} ">Upcoming Events</a></li>
             <li><a href=" {% url 'techno:become_a_campus_ambassador' %} ">Be a Campus Ambassador</a></li>
             <li><a href=" {% url 'techno:request_a_workshop_view' %} ">Organize a Workshop</a></li>
             <!-- <li><a href=" {% url 'techno:upcoming_events_temporary' %} ">Certificate Verification</a></li> -->
             <li><a href=" {% url 'techno:contact_us' %}">Contact Us</a></li>
             <!-- <li  class = "mobile-display" style="position:absolute; right:100px; top:5px; "><a href="{%url 'techno:index' %}"><img src=" {% static 'img/Logos/DIGIINFY.png' %} " alt="" title="" style = "height:55px;"></a></li> -->
        </ul>
      </nav><!-- #nav-menu-container -->
        </div>
    </div>
  </header><!-- #header -->


{% block content %}{% endblock %}


  <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 text-lg-left text-center">
          <div class="copyright">
            &copy;Copyright 2016 <strong> DiGi Infy. </strong> All Rights Reserved.
          </div>
          <!-- <div  class = "mobile-display" style="position:absolute; right:100px; top:5px; "><a href="{%url 'techno:index' %}"><img src=" {% static 'img/Logos/DIGIINFY.png' %} " alt="" title="" style = "height:55px;"></a></div>
        -->
          <div class="credits">
           Designed by <a href="https://www.linkedin.com/in/ishan-rai-468231157/">Ishan</a> &amp; <a href="https://www.linkedin.com/in/durgesh-kumar-807233157/">Durgesh</a>
          </div>
        </div>
        <div class="col-lg-6">
          <nav class="footer-links text-lg-right text-center pt-2 pt-lg-0">
            <a href="{%url 'techno:index' %}" class="scrollto">Home</a>
            <a href="{% url 'techno:about'  %}" class="scrollto">About</a>
            <a href="#">Privacy Policy</a>
            <a href="#">Terms of Use</a>
          </nav>
        </div>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
  <script src="{% static 'lib/magnific-popup/magnific-popup.min.js' %}"></script>
  <script src="{% static 'lib/slick/slick.js' %}"></script>
  <script src="{% static 'lib/slick/slick.min.js' %}"></script>
  <script src="{% static 'lib/particle-js/particles.min.js' %}"></script>
  <script src="{% static 'lib/particle-js/app.js' %}"></script>

  <script src= "{% static 'js/jquery.scrollex.min.js' %}"  ></script>
  <script src= "{% static 'js/skel.min.js' %}" ></script>
  <script src= "{% static 'js/util.js' %}" ></script>
  <script src= "{% static 'js/main.js' %}" ></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js' %}"></script>

  <!-- Template Main Javascript File -->
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122862612-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122862612-1');
</script>


</body>
</html>

technoadvance3/templates/upcoming_events.html
<head>
<style>
  @import url(https://fonts.googleapis.com/css?family=Raleway:300,700);

body {
  width:100%;
  height:100%;
  background:#48A9E6;
  font-family: 'Raleway', sans-serif;
  font-weight:300;
  margin:0;
  padding:0;
}

#title {
  text-align:center;
  font-size:40px;
  margin-top:40px;
  margin-bottom:-40px;
  position:relative;
  color:#fff;
}

.circles:after {
  content:'';
  display:inline-block;
  width:100%;
  height:100px;
  background:#fff;
  position:absolute;
  top:-50px;
  left:0;
  transform:skewY(-4deg);
  -webkit-transform:skewY(-4deg);
}

.circles { 
  background:#fff;
  text-align: center;
  position: relative;
  margin-top:-60px;
  box-shadow:inset -1px -4px 4px rgba(0,0,0,0.2);
}

.circles p {
  font-size: 240px;
  color: #fff;
  padding-top: 60px;
  position: relative;
  z-index: 9;
  line-height: 100%;
}

.circles p small { 
  font-size: 40px; 
  line-height: 100%; 
  vertical-align: top;   
}

.circles .circle.small {
  width: 140px;
  height: 140px;
  border-radius: 50%;
  background: #48A9E6;
  position: absolute;
  z-index: 1;
  top: 80px;
  left: 50%;
  animation: 7s smallmove infinite cubic-bezier(1,.22,.71,.98); 
  -webkit-animation: 7s smallmove infinite cubic-bezier(1,.22,.71,.98);
  animation-delay: 1.2s;
  -webkit-animation-delay: 1.2s;
}

.circles .circle.med {
  width: 200px;
  height: 200px;
  border-radius: 50%;
  background: #48A9E6;
  position: absolute;
  z-index: 1;
  top: 0;
  left: 10%;
  animation: 7s medmove infinite cubic-bezier(.32,.04,.15,.75); 
  -webkit-animation: 7s medmove infinite cubic-bezier(.32,.04,.15,.75);
  animation-delay: 0.4s;
  -webkit-animation-delay: 0.4s;
}

.circles .circle.big {
  width: 400px;
  height: 400px;
  border-radius: 50%;
  background: #48A9E6;
  position: absolute;
  z-index: 1;
  top: 200px;
  right: 0;
  animation: 8s bigmove infinite; 
  -webkit-animation: 8s bigmove infinite;
  animation-delay: 3s;
  -webkit-animation-delay: 1s;
}

@-webkit-keyframes smallmove {
  0% { top: 10px; left: 45%; opacity: 1; }
  25% { top: 300px; left: 40%; opacity:0.7; }
  50% { top: 240px; left: 55%; opacity:0.4; }
  75% { top: 100px; left: 40%;  opacity:0.6; }
  100% { top: 10px; left: 45%; opacity: 1; }
}
@keyframes smallmove {
  0% { top: 10px; left: 45%; opacity: 1; }
  25% { top: 300px; left: 40%; opacity:0.7; }
  50% { top: 240px; left: 55%; opacity:0.4; }
  75% { top: 100px; left: 40%;  opacity:0.6; }
  100% { top: 10px; left: 45%; opacity: 1; }
}

@-webkit-keyframes medmove {
  0% { top: 0px; left: 20%; opacity: 1; }
  25% { top: 300px; left: 80%; opacity:0.7; }
  50% { top: 240px; left: 55%; opacity:0.4; }
  75% { top: 100px; left: 40%;  opacity:0.6; }
  100% { top: 0px; left: 20%; opacity: 1; }
}

@keyframes medmove {
  0% { top: 0px; left: 20%; opacity: 1; }
  25% { top: 300px; left: 80%; opacity:0.7; }
  50% { top: 240px; left: 55%; opacity:0.4; }
  75% { top: 100px; left: 40%;  opacity:0.6; }
  100% { top: 0px; left: 20%; opacity: 1; }
}

@-webkit-keyframes bigmove {
  0% { top: 0px; right: 4%; opacity: 0.5; }
  25% { top: 100px; right: 40%; opacity:0.4; }
  50% { top: 240px; right: 45%; opacity:0.8; }
  75% { top: 100px; right: 35%;  opacity:0.6; }
  100% { top: 0px; right: 4%; opacity: 0.5; }
}
@keyframes bigmove {
  0% { top: 0px; right: 4%; opacity: 0.5; }
  25% { top: 100px; right: 40%; opacity:0.4; }
  50% { top: 240px; right: 45%; opacity:0.8; }
  75% { top: 100px; right: 35%;  opacity:0.6; }
  100% { top: 0px; right: 4%; opacity: 0.5; }
}

</style>
</head>

<body>
  <section id="not-found">
    <div id="title"> &bull;</div>
    <div class="circles">
      <p><br>
       <small> Stay Tuned Coming Soon</small>
      </p>
      <span class="circle big"></span>
      <span class="circle med"></span>
      <span class="circle small"></span>
    </div>
  </section>
 </body>

technoadvance3/templates/workshop.html
{% extends "header3.html"%}
{% load staticfiles %}

{% load tags %}
{% block content %}


<style>
.box {
    border-radius: 4px;
    margin-bottom: 2em;
    background: #2c2c32;
    text-align: center;
    -webkit-box-shadow: 0px 0px 7.33px 12.67px rgba(0, 0, 0, 0.12);box-shadow: 0px 0px 7.33px 12.67px rgba(0, 0, 0, 0.12);border-radius:10px;}

    .box > :last-child,
    .box > :last-child > :last-child,
    .box > :last-child > :last-child > :last-child {
      margin-bottom: 0;
    }

    .box .image.fit {
      margin: 0;
    }

    .box .image img {
      border-radius: 4px 4px 0 0;
    }

    .box .inner {
      padding: 1.5em;
      width: 100% !important;
    }

      @media screen and (max-width: 480px) {

        .box .inner {
          padding: 1em;
        }

      }

    .box.alt {
      border: 0;
      border-radius: 0;
      padding: 0;
    }

/* Icon */

  .icon {
    text-decoration: none;
    border-bottom: none;
    position: relative;
  }

    .icon:before {
      -moz-osx-font-smoothing: grayscale;
      -webkit-font-smoothing: antialiased;
      font-family: FontAwesome;
      font-style: normal;
      font-weight: normal;
      text-transform: none !important;
    }

    .icon > .label {
      display: none;
    }

/* Image */

  .image {
    border-radius: 4px;
    border: 0;
    display: inline-block;
    position: relative;
  }

    .image img {
      border-radius: 4px;
      display: block;
    }

    .image.left, .image.right {
      max-width: 40%;
    }

      .image.left img, .image.right img {
        width: 100%;
      }

    .image.left {
      float: left;
      padding: 0 1.5em 1em 0;
      top: 0.25em;
    }

    .image.right {
      float: right;
      padding: 0 0 1em 1.5em;
      top: 0.25em;
    }

    .image.fit {
      display: block;
      margin: 0 0 2em 0;
      width: 100%;
    }

      .image.fit img {
        width: 100%;
      }

    .image.main {
      display: block;
      margin: 0 0 3em 0;
      width: 100%;
    }

      .image.main img {
        width: 100%;
      }
.button{

    width: 100%;
    display: block;
    background: #70c7be;
    padding: 10px;
    border-radius: 5px;

}
.button1{
  width: 100%;
    display: block;
    padding: 10px;
    border-radius: 5px;

  background: #7f92cf;
}
.button2{
  width: 100%;
    display: block;
    padding: 10px;
    border-radius: 5px;

  background: #9d7ed0;
}

</style>
<section class="banner full" style="padding: 0;min-height: 0vh;height: 60vh !important;">
        <article>
          <img src=" {% static 'img/workshop2.jpg' %}" alt="" style="height:50%!important" />
          <div class="inner">
            <header class = "wow fadeInUp">
              <h3 style="font-size:61px !important;" > <strong>Workshops</strong> </h3>
              <p>Few workshops that we offer. Certainly not exhaustive.</p>
              <a href="{% url 'techno:about'  %}">
              </a>
            </header>
          </div>
        </article>
        
     
      </section>
   <div class = "container wow fadeInUp" style="padding-top: 20px;">
   {% for workshop in workshops %}    
     {% ifequal forloop.counter0|modulo:3 0 %}
           <div class = "row">
           {% endifequal %}
                   <div class="category-section col-xs-12 col-sm-6 col-md-4">
                      <div class="box">
                        <a href= "{% url 'techno:workshops' id=workshop.id %}" class="image fit"><img src=" {{ workshop.workshop_image.url }} " alt="" /></a>
                        <div class="inner">
                          <h4 class="text-light"> {{ workshop.workshop_title }}  </h4>
                          <p class="text-secondary"> {{ workshop.workshop_about|truncatewords:20 }} </p>
                          
                          {% if forloop.counter|divisibleby:2 %}
                          <a href="{% url 'techno:workshops' id=workshop.id %}" class="button1 fit text-light" >Know More</a>
                          {% else %}
                          <a href="{% url 'techno:workshops' id=workshop.id %}" class="button2 fit text-light" >Know More</a>
                          {% endif %}
                        </div>
                      </div>

                   </div>                                                 
                 {% ifequal forloop.counter0|modulo:3 2 %}
           </div>
             {% endifequal %}
   {% endfor %}
   </div>
   </div>
<style>
  #clients img{
    border:1px solid black !important;
    height:120px;
    width:150px;
    -webkit-box-shadow: 0px 0px 29px 7px rgba(0,0,0,0.31);
    -moz-box-shadow: 0px 0px 29px 7px rgba(0,0,0,0.31);
    box-shadow: 0px 0px 29px 7px rgba(0,0,0,0.31);
  }
  .client-slider p{
    font-size: 18px;
    text-align: center;
    line-height: 2.5;
  }
</style>
<section id = "clients" style = "margin-top:45px" >
    <div class="container">
    <div class="section-header">
          <h3 class="section-title">Who we've worked with</h3>
          <p class="section-description"> We are highly thankful to our partners who believed in us and gave us a chance to engage ourselves in their events. Let’s introduce you to some of India’s best institutes. </p>
          <span class="section-divider"></span>
            
        <div class = "client-slider" >                
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/apogee.jpg' %}" alt=""><p>BITS Pilani</p></div>
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/cogni.png' %}"  alt="" ><p>IIT Roorkee</p></div>
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/techkriti.png' %}" alt=""><p>IIT Kanpur</p></div>
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/technext.jpg' %}"  alt=""><p>IIT (BHU)</p></div>
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/techniche.jpg' %}"  alt=""><p>IIT Guwahati</p></div>
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/wissenaire.png' %}"  alt=""><p>IIT Bhubaneswar</p></div>
        <div style="margin-right: 2.5vw;margin-left: 2.5vw;"><img src = "{% static 'img/clients/exodia.png' %}"  alt=""><p>IIT Mandi</p></div>
        
        </div>
      </div>
  </div>
  <div style = "height:70px"></div> 
</section>
 
<section id="contact">
      <div class="container">
        <div class="section-header">
          <h3 class="section-title">GET IN TOUCH</h3>
          <span class="section-divider"></span>
       </div>
        <div class="row wow fadeInUp">

          <div class="col-lg-4 col-md-6">
            <div class="contact-about">
             <h5><strong>Diginique Techno Solutions</strong></h5>
              <h6>Unique Advancement to Your Career</h6>
              <br>
              <p class = "text-justify"> <strong>Diginique, </strong> A domain of <strong>DiGi Infy,</strong> is a fast growing organization founded by <strong>IIT Graduates</strong> and <strong>Google AdWords </strong> certified consultant, which aims to revolutionize the field of technology and management seamlessly.</p>
              <div class="social-links">
                <a href="https://www.facebook.com/diginique2016/" class="facebook"><i class="fa fa-facebook"></i></a>
                <a href="https://plus.google.com/114057180279997984204" class="google-plus"><i class="fa fa-google-plus"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6">
            <div class="info">
              <div>
                <i class="ion-ios-location-outline"></i>
                <p><strong>Head Office:</strong><br>118/190, Kaushalpuri Kanpur - 201812</p>
              </div>
              <div>
                <i class="ion-ios-email-outline"></i>
                <p><strong>For support or queries write us at:</strong> <br>diginique2016@gmail.com<br>support@diginique.com</p>
              </div>

              <div>
                <i class="ion-ios-telephone-outline"></i>
                <p><strong>Give us a call at:</strong><br>

               +91-7985432632 <br> +91-9758961520</p>
              </div>

            </div>
          </div>
          
          <div class="col-lg-5 col-md-12 contact-about">
            <p><strong>Please fill in the form so that we may contact you</strong></p>
            <div class="form">
              <div id="sendmessage">Your message has been sent. Thank you!</div>
              <div id="errormessage"></div>
              <form action="" method="post" role="form" class="contactForm">
                {% csrf_token %}
                <div class="form-row">
                  <div class="form-group col-lg-6">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                    <div class="validation"></div>
                  </div>
                  <div class="form-group col-lg-6">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                    <div class="validation"></div>
                  </div>
                </div>
                <div class="form-group">
                  <input type="Number" class="form-control" name="contact_number" id="contact_number" placeholder="Contact Number" data-rule="minlen:4" data-msg="Please enter a correct phone number." />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                  <div class="validation"></div>
                </div>
              <input class="btn btn-outline-dark btn-block btn-block" type="submit" value="Submit" />  
              </form>
            </div>
          </div>

        </div>


          

      </div>
    </section><!-- #contact -->

{% endblock %}